### ISSUE TITLE
Christiane & Studierende zur Begehung einladen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-2017#26]

**Comment by marioww42** [comment]
**11:15-12:15 Uhr**
1.    Fachschaft
2.    Studierende
3.    Absolventen (nicht Mitarbeiter)

**16:30-17:00 Uhr**
Alle interessierten

[Ablaufplan TH Köln BaMaMedieninformatik 25.04.2017.pdf](https://github.com/th-koeln/mi-2017/files/825013/Ablaufplan.TH.Koln.BaMaMedieninformatik.25.04.2017.pdf)
