### ISSUE TITLE
Catering für Begehung organisieren

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-2017#27]

**Comment by marioww42** [comment]
> Liebe Julia,
>  
> da vertraue ich ganz auf Deine Erfahrung – Suppe und Brötchen (auch einige „Vegane“) sind OK. Ich denke, das außer den 5 Gutachtern noch 5 aus unseren Reihen zu Mittag essen werden, also sollten 10 Portionen reichen. Die Gutachter sollten aber wie gesagt in einem eigenen Raum essen (und konferieren) können.
> @Christian: was meinst Du?

passt!
Danke


>  
> Viele Grüße
>  
> Mario
> --
> Prof. Dr. Mario Winter
> TH Köln
>  
> Von: Julia Diedrich
> Gesendet: Montag, 20. Februar 2017 11:22
> An: mario.winter@th-koeln.de
> Betreff: Re: Reakkr. MI BA und MA: Vor-Ort-Begehung am 25.04.2017
>  
> Lieber Mario,
> 
> hmmmm... ich weiß nicht, ob das mit dem "Aussuchen" und der Mensakarte so praktikabel ist? Wie wäre es denn, wenn wir eine Suppe bestellen und ein paar belegte Brötchen?
> 
> Das kann die Mensa auch gut vorbereiten. Auch würde ich eh alles in der Mensa ordern, dann wäre das ein Abwasch. Wieviele Personen sind es denn insgesamt (inkl. der 5 Gutachter)?
> 
>  
> 
> Viele Grüße
> 
> Julia
> 
>  
> 
>  
> Am 01.02.2017 um 16:40 schrieb mario.winter@th-koeln.de:
> Liebe Julia, liebe Frau Lach,
>  
> für die Reakkreditierung der Medieninformatik BA+MA an der Fakultät 10 wurde uns von der Akkreditierungskommission ASIIN als Termin für die Vor-Ort-Begehung der Dienstag, 25. April 2017 genannt (s. Anlage). 
>  
> Dafür würden wir für die Sitzungen von 8:00-18:00 Uhr gerne Raum 1.122 (Kienbaum-Saal) sowie für die internen Gespräche und die Mittagspause der Gutachter einen benachbarten kleineren Raum für 5 Pers. reservieren.
>  
> Im Kienbaum-Saal dann bitte das „übliche“ Catering (Kaffee, Teewasser und -beutel, Mineralwasser still und medium, einige Säfte, Gebäck sowie Tassen, Gläser und kleine Teller …). 
>  
> Für Mittags wäre es prima, wenn für die 5 Gutachter der ASIIN ein warmes Essen aus der Mensa gebracht und in dem kleineren Raum serviert werden könnte (morgens dann anhand der Mensa-Karte auswählen lassen).
>  
> Würdet ihr das für uns organisieren? Fällt euch sonst noch etwas dazu ein?
>  
> Viele Grüße und vielen Dank im voraus
>  
> Mario
>
