### ISSUE TITLE
Kümmerer erarbeiten Liste mit den notwendigen Lehrveranstaltungen für Projekte und sprechen mit geeigneten Lehrenden

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-2017#3]

**Comment by martineisemann** [comment]
Sind mit den notwendigen Lehrveranstaltungen die Veranstaltungen parallel zum MI MA Projekt im grünen Bereich gemeint? Also Projektmanagement, Beautiful Code, etc...?
