### ISSUE TITLE
Modulbeschreibungen Feintuning

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-2017#30]
Bitte prüfen:

- ob die Lehrformen korrekt angeben sind, z.B. Workshop, Flipped Classroom
- ob die Kompetenzen aus der Ziele Module Matrix auch in der Modulbeschreibung auftaucht
- ob die Lernziele den Dreiklang "Was", "Wie tief", "Warum"

**Comment by marioww42** [comment]
Bitte alle noch einmal die Ziele-Matritzen für BA und MA überprüfen (nur jeweils das "Haupt-"Arbeitsblatt):
BA: https://docs.google.com/spreadsheets/d/1wjIL7WIGBU0Oqz71xT2qFYz2nvhmkpHgZ9zfKjFaGy0/edit#gid=1624050223
MA: https://docs.google.com/spreadsheets/d/1zNzHhjq93ZJWjozifDGu4KcwLPn1RY6efZJAblKIq0E/edit#gid=1420497404
