### ISSUE TITLE
Modulbeschreibungen Projekte

### ISSUE THREAD

**Issue by marioww42** [th-koeln/mi-2017#33]
Es gibt nur noch die drei "allgemeinen" Projektbeschreibungen, und die Reihenfolge der Projekte ist  - aus Studierendensicht - immer Konzept, Entwicklung, Verwertung (egal ob Start WiSe oder SoSe). Weil:
- Der Studienverlaufsplan sollte einfach sein. Jeder Studierende muss je ein Projekt je Fragestellung durchführen.
- Studierende können der Fragestellung in "beliebeigen" Projekten nachgehen, z.B. kann ein Studierender Vision und Konzept reviewen und überarbeiten/ergänzen, obwohl andere das Projekt bereits unter der Frage "Entwicklung" bearbeiten.
- so ermöglichen wir auch agile Vorgehensweisen.
- Im Projekt-Kickoff können wir ja dann lenken und z.B. ein Projekt gut geeignet für eine der drei Fragestellungeun und einen (oder mehrere) Studienschwerpunkte) anbieten.

**Comment by martineisemann** [comment]
Das Modul heisst doch "Assessment/Evaluation, Forschung und Verwertung im Kontext des Studienschwerpunkts", in der Beschreibung taucht Forschung gar nicht mehr auf, weder in der Kurzbeschreibung, noch im Inhalt. Das finde ich sollten wir aber unbedingt wieder hineinnehmen, der Konsens war doch eigentlich, dass das ein wichtiger Eckpfeiler in der Ausrichtung der TH werden sollte.
