### ISSUE TITLE
Medieninformatik Positionspapier

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-2017#5]

**Comment by kf-fhkoeln** [comment]
Die Medieninformatik befasst sich mit
¥	der Analyse, Konzeption, Realisierung und Evaluation von interaktiven, oft web-basierten und multimedialen Mensch-Computer-Systemen sowie Systemen zur computer-mediierten multimedialen Mensch-Mensch-Kommunikation,
¥	Methoden und Werkzeugen zur Konzeption, Gestaltung, Produktion, Speicherung und Verteilen von Digitalen Medien sowie
¥	Zielen, Anforderungen, Wirkungen Digitaler Medien und hier insbesondere des Web für Menschen, Umwelt, Gesellschaft und Unternehmen.

Der Bachelorstudiengang soll Absolventen befähigen, in interdisziplinären Teams meist web-basierte Prozesse und Systeme zur Produktion, Bearbeitung und Distribution medienbasierter Informationen aus informatischen, ökonomischen und sozialen Perspektiven zu analysieren, konzipieren, realisieren und adaptieren; ggf. betreiben sie diese Systeme auch.. 

Der Masterstudiengang Medieninformatik soll die Absolventinnen und Absolventen befähigen, an der Analyse komplexer informatik-spezifischer Aufgabenstellungen im Kontext interaktiver, oft web-basierter multimedialer Systeme an leitender Stelle in interdisziplinären Teams mitzuwirken, Lösungskonzepte verantwortlich zu entwerfen und zu realisieren, kritisch einzuordnen, in der fachlichen Öffentlichkeit zu kommunizieren und verwerten zu können und interdisziplinäre Entwicklungsteams zu führen.
