### ISSUE TITLE
Empfohlene Voraussetzungen prüfen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-2017#56]

**Comment by kf-fhkoeln** [comment]
Hab mir das gerade nochmal angesehen: ich denke an diesem Platz würden primär Kenntnisse aus anderen Master Modulen als Voraussetzung formuliert. Da kommen wir aber mit unserer flexiblen Studienstruktur in Konflikt. Daher scheint es mir besser zu vertreten, dass wir i.d.R. kein Voraussetzungen formulieren. Der einzige Punkt könnte das Projekt "Verwertung" sein; hier könnten wir voraussetzen, dass eines der anderen beiden Projekte absolviert ist.

**Comment by kf-fhkoeln** [comment]
.. sorry .. aus Versehen geschlosssen
