### ISSUE TITLE
Rüdel wegen Trennung der Bachelor und Master

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-2017#6]

**Comment by marioww42** [comment]
Sind nun in sciebo unter
[https://th-koeln.sciebo.de/index.php/apps/files?dir=/ReakkreditierungMI_sciebo/Zahlen%20%26%20Statistiken](url)
MI-BA:
https://th-koeln.sciebo.de/remote.php/webdav/ReakkreditierungMI_sciebo/Zahlen%20%26%20Statistiken/F10_Abs-Medieninformatik_BA_W16-17.pdf
MI-MA:
https://th-koeln.sciebo.de/remote.php/webdav/ReakkreditierungMI_sciebo/Zahlen%20%26%20Statistiken/F10_Abs-Medieninformatik_MA_W16-17.pdf
