### ISSUE TITLE
Kapazität erfassen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-2017#7]

**Comment by martineisemann** [comment]
Haben wir hierfür bereits ein Dokument, oder soll das jeder einfach für sich machen für die nächste Sitzung?

**Comment by cnoss** [comment]
Da hatte ich schon mal was rumgeschickt vor geraumer Zeit. Das war so eine Number Liste. Ich glaub, da hast Du schon was eingetragen. können wir gleich sprechen.
